scrape_configs:
  - job_name: postgres_exporter
    static_configs:
      - targets: ["172.20.55.4:9187"]
    scrape_interval: 5s 
  - job_name: pgscv
    static_configs:
      - targets: ["172.20.55.6:9890"]
    scrape_interval: 5s 