apiVersion: 1

datasources:
  - name: k6influxdb
    type: influxdb
    access: proxy
    database: k6
    url: http://172.20.55.1:8086
  
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.20.55.5:9090
